apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: kafka-consumer-workflow
spec:
  entrypoint: kafka-consumer
  templates:
    - name: kafka-consumer
      container:
        image: library/kafka-consumer:latest
        command: ["python", "-u"]
        args: ["kafka_consumer.py"]
        imagePullPolicy: IfNotPresent
